import { create } from 'zustand';

export const LOCALE_KEYS = {
  ADD_TO_CART: 'ADD_TO_CART',
  OUT_OF_STOCK: 'OUT_OF_STOCK',
  TOTAL: 'TOTAL',
  DELIVERY_OPTIONS: 'DELIVERY_OPTIONS',
  SHOP: 'SHOP',
  ABOUT: 'ABOUT',
  CONTACT: 'CONTACT',
  ORDERS: 'ORDERS',
  CART: 'CART',
  CART_EMPTY: 'CART_EMPTY',
  CHECKOUT: 'CHECKOUT',
  HERO_TITLE: 'HERO_TITLE',
  HERO_SUBTITLE: 'HERO_SUBTITLE',
  PRODUCTS_TITLE: 'PRODUCTS_TITLE',
  PRICE_CURRENCY: 'PRICE_CURRENCY',
  SEARCH_PLACEHOLDER: 'SEARCH_PLACEHOLDER',
  ALL_CATEGORIES: 'ALL_CATEGORIES',
  CAT_COFFEE: 'CAT_COFFEE',
  CAT_EQUIPMENT: 'CAT_EQUIPMENT',
  CAT_SWEETS: 'CAT_SWEETS',
  CHECKOUT_TITLE: 'CHECKOUT_TITLE',
  CHECKOUT_FORM_EMAIL: 'CHECKOUT_FORM_EMAIL',
  CHECKOUT_FORM_ADDRESS: 'CHECKOUT_FORM_ADDRESS',
  CHECKOUT_FORM_PHONE: 'CHECKOUT_FORM_PHONE',
  PLACE_ORDER: 'PLACE_ORDER',
  ORDER_SUCCESS_TITLE: 'ORDER_SUCCESS_TITLE',
  ORDER_SUCCESS_SUBTITLE: 'ORDER_SUCCESS_SUBTITLE',
  BACK_TO_SHOP: 'BACK_TO_SHOP',
  LOYALTY_POINTS: 'LOYALTY_POINTS',
  POINTS_EARNED_TEMPLATE: 'POINTS_EARNED_TEMPLATE',
  CONFIRMATION_SENT_TO: 'CONFIRMATION_SENT_TO',
  ACCOUNT_CREATED_TITLE: 'ACCOUNT_CREATED_TITLE',
  ACCOUNT_CREATED_SUBTITLE: 'ACCOUNT_CREATED_SUBTITLE',
  ABOUT_TITLE: 'ABOUT_TITLE',
  ABOUT_TEXT: 'ABOUT_TEXT',
  CONTACT_TITLE: 'CONTACT_TITLE',
  CONTACT_TEXT: 'CONTACT_TEXT',
  CONTACT_ADDRESS: 'CONTACT_ADDRESS',
  CONTACT_PHONE: 'CONTACT_PHONE',
  CONTACT_EMAIL: 'CONTACT_EMAIL',
  AUTH_WELCOME_BACK: 'AUTH_WELCOME_BACK',
  AUTH_JOIN_FAMILY: 'AUTH_JOIN_FAMILY',
  AUTH_LOGIN_SUBTITLE: 'AUTH_LOGIN_SUBTITLE',
  AUTH_REGISTER_SUBTITLE: 'AUTH_REGISTER_SUBTITLE',
  AUTH_FULL_NAME: 'AUTH_FULL_NAME',
  AUTH_EMAIL: 'AUTH_EMAIL',
  AUTH_PASSWORD: 'AUTH_PASSWORD',
  AUTH_SIGN_IN: 'AUTH_SIGN_IN',
  AUTH_CREATE_ACCOUNT: 'AUTH_CREATE_ACCOUNT',
  AUTH_NO_ACCOUNT: 'AUTH_NO_ACCOUNT',
  AUTH_HAVE_ACCOUNT: 'AUTH_HAVE_ACCOUNT'
};

const translations = {
  en: {
    [LOCALE_KEYS.ADD_TO_CART]: 'Add to Cart',
    [LOCALE_KEYS.OUT_OF_STOCK]: 'Out of Stock',
    [LOCALE_KEYS.TOTAL]: 'Total',
    [LOCALE_KEYS.DELIVERY_OPTIONS]: 'Delivery options',
    [LOCALE_KEYS.SHOP]: 'Shop',
    [LOCALE_KEYS.ABOUT]: 'About',
    [LOCALE_KEYS.CONTACT]: 'Contact',
    [LOCALE_KEYS.ORDERS]: 'Orders',
    [LOCALE_KEYS.CART]: 'Cart',
    [LOCALE_KEYS.CART_EMPTY]: 'Your cart is empty',
    [LOCALE_KEYS.CHECKOUT]: 'Checkout',
    [LOCALE_KEYS.HERO_TITLE]: 'Crafted for Clarity',
    [LOCALE_KEYS.HERO_SUBTITLE]: 'Discover our meticulously roasted single-origin coffees, designed to elevate your daily ritual.',
    [LOCALE_KEYS.PRODUCTS_TITLE]: 'Our Collection',
    [LOCALE_KEYS.PRICE_CURRENCY]: '$',
    [LOCALE_KEYS.SEARCH_PLACEHOLDER]: 'Search products...',
    [LOCALE_KEYS.ALL_CATEGORIES]: 'All',
    [LOCALE_KEYS.CAT_COFFEE]: 'Coffee',
    [LOCALE_KEYS.CAT_EQUIPMENT]: 'Equipment',
    [LOCALE_KEYS.CAT_SWEETS]: 'Sweets',
    [LOCALE_KEYS.CHECKOUT_TITLE]: 'Checkout',
    [LOCALE_KEYS.CHECKOUT_FORM_EMAIL]: 'Email Address',
    [LOCALE_KEYS.CHECKOUT_FORM_ADDRESS]: 'Delivery Address',
    [LOCALE_KEYS.CHECKOUT_FORM_PHONE]: 'Phone Number',
    [LOCALE_KEYS.PLACE_ORDER]: 'Place Order',
    [LOCALE_KEYS.ORDER_SUCCESS_TITLE]: 'Order Placed Successfully!',
    [LOCALE_KEYS.ORDER_SUCCESS_SUBTITLE]: 'Thank you for your purchase. We are preparing your order.',
    [LOCALE_KEYS.BACK_TO_SHOP]: 'Back to Shop',
    [LOCALE_KEYS.LOYALTY_POINTS]: 'You earned points!',
    [LOCALE_KEYS.POINTS_EARNED_TEMPLATE]: 'You earned {points} bonus points from this order!',
    [LOCALE_KEYS.CONFIRMATION_SENT_TO]: 'Confirmation sent to {email}.',
    [LOCALE_KEYS.ACCOUNT_CREATED_TITLE]: 'Account Created',
    [LOCALE_KEYS.ACCOUNT_CREATED_SUBTITLE]: 'Welcome to the family! You are now logged in.',
    [LOCALE_KEYS.ABOUT_TITLE]: 'Our Story',
    [LOCALE_KEYS.ABOUT_TEXT]: 'We started with a simple idea: coffee should be transparent, from farm to cup. Our roasters work directly with farmers to ensure fair wages and exceptional quality. Every bean we roast is a testament to our dedication to the craft.',
    [LOCALE_KEYS.CONTACT_TITLE]: 'Get in Touch',
    [LOCALE_KEYS.CONTACT_TEXT]: 'Have questions about our roasts or need help with your brewing equipment? We are here to help.',
    [LOCALE_KEYS.CONTACT_ADDRESS]: '123 Roaster Way, Coffee District, NY 10001',
    [LOCALE_KEYS.CONTACT_PHONE]: '+1 (555) 123-4567',
    [LOCALE_KEYS.CONTACT_EMAIL]: 'hello@onyxroasters.com',
    [LOCALE_KEYS.AUTH_WELCOME_BACK]: 'Welcome Back',
    [LOCALE_KEYS.AUTH_JOIN_FAMILY]: 'Join the Family',
    [LOCALE_KEYS.AUTH_LOGIN_SUBTITLE]: 'Enter your details to access your account',
    [LOCALE_KEYS.AUTH_REGISTER_SUBTITLE]: 'Create an account to start your coffee journey',
    [LOCALE_KEYS.AUTH_FULL_NAME]: 'Full Name',
    [LOCALE_KEYS.AUTH_EMAIL]: 'Email Address',
    [LOCALE_KEYS.AUTH_PASSWORD]: 'Password',
    [LOCALE_KEYS.AUTH_SIGN_IN]: 'Sign In',
    [LOCALE_KEYS.AUTH_CREATE_ACCOUNT]: 'Create Account',
    [LOCALE_KEYS.AUTH_NO_ACCOUNT]: "Don't have an account? Sign up",
    [LOCALE_KEYS.AUTH_HAVE_ACCOUNT]: "Already have an account? Sign in"
  },
  uk: {
    [LOCALE_KEYS.ADD_TO_CART]: 'Додати в кошик',
    [LOCALE_KEYS.OUT_OF_STOCK]: 'Немає в наявності',
    [LOCALE_KEYS.TOTAL]: 'Разом',
    [LOCALE_KEYS.DELIVERY_OPTIONS]: 'Варіанти доставки',
    [LOCALE_KEYS.SHOP]: 'Магазин',
    [LOCALE_KEYS.ABOUT]: 'Про нас',
    [LOCALE_KEYS.CONTACT]: 'Контакти',
    [LOCALE_KEYS.ORDERS]: 'Замовлення',
    [LOCALE_KEYS.CART]: 'Кошик',
    [LOCALE_KEYS.CART_EMPTY]: 'Ваш кошик порожній',
    [LOCALE_KEYS.CHECKOUT]: 'Оформити замовлення',
    [LOCALE_KEYS.HERO_TITLE]: 'Створено для ясності',
    [LOCALE_KEYS.HERO_SUBTITLE]: 'Відкрийте для себе нашу ретельно обсмажену каву одного походження, створену для вашого щоденного ритуалу.',
    [LOCALE_KEYS.PRODUCTS_TITLE]: 'Наша колекція',
    [LOCALE_KEYS.PRICE_CURRENCY]: '₴',
    [LOCALE_KEYS.SEARCH_PLACEHOLDER]: 'Пошук товарів...',
    [LOCALE_KEYS.ALL_CATEGORIES]: 'Всі',
    [LOCALE_KEYS.CAT_COFFEE]: 'Кава',
    [LOCALE_KEYS.CAT_EQUIPMENT]: 'Обладнання',
    [LOCALE_KEYS.CAT_SWEETS]: 'Солодощі',
    [LOCALE_KEYS.CHECKOUT_TITLE]: 'Оформлення',
    [LOCALE_KEYS.CHECKOUT_FORM_EMAIL]: 'Електронна пошта',
    [LOCALE_KEYS.CHECKOUT_FORM_ADDRESS]: 'Адреса доставки',
    [LOCALE_KEYS.CHECKOUT_FORM_PHONE]: 'Номер телефону',
    [LOCALE_KEYS.PLACE_ORDER]: 'Зробити замовлення',
    [LOCALE_KEYS.ORDER_SUCCESS_TITLE]: 'Замовлення успішно оформлено!',
    [LOCALE_KEYS.ORDER_SUCCESS_SUBTITLE]: 'Дякуємо за покупку. Ми готуємо ваше замовлення.',
    [LOCALE_KEYS.BACK_TO_SHOP]: 'Повернутися до магазину',
    [LOCALE_KEYS.LOYALTY_POINTS]: 'Ви отримали бонуси!',
    [LOCALE_KEYS.POINTS_EARNED_TEMPLATE]: 'Ви отримали {points} бонусних балів за це замовлення!',
    [LOCALE_KEYS.CONFIRMATION_SENT_TO]: 'Підтвердження надіслано на {email}.',
    [LOCALE_KEYS.ACCOUNT_CREATED_TITLE]: 'Акаунт створено',
    [LOCALE_KEYS.ACCOUNT_CREATED_SUBTITLE]: 'Ласкаво просимо до нашої родини! Ви успішно увійшли в систему.',
    [LOCALE_KEYS.ABOUT_TITLE]: 'Наша історія',
    [LOCALE_KEYS.ABOUT_TEXT]: 'Ми почали з простої ідеї: кава має бути прозорою, від ферми до чашки. Наші обсмажувальники працюють безпосередньо з фермерами, щоб гарантувати справедливу оплату та виняткову якість.',
    [LOCALE_KEYS.CONTACT_TITLE]: 'Зв\'яжіться з нами',
    [LOCALE_KEYS.CONTACT_TEXT]: 'Маєте питання щодо нашого обсмаження або потрібна допомога з обладнанням? Ми тут, щоб допомогти.',
    [LOCALE_KEYS.CONTACT_ADDRESS]: 'вул. Ростерська 123, Кавовий район, Київ 01001',
    [LOCALE_KEYS.CONTACT_PHONE]: '+38 (044) 123-4567',
    [LOCALE_KEYS.CONTACT_EMAIL]: 'hello@onyxroasters.ua',
    [LOCALE_KEYS.AUTH_WELCOME_BACK]: 'З поверненням',
    [LOCALE_KEYS.AUTH_JOIN_FAMILY]: 'Приєднуйтесь до родини',
    [LOCALE_KEYS.AUTH_LOGIN_SUBTITLE]: 'Введіть свої дані, щоб увійти в акаунт',
    [LOCALE_KEYS.AUTH_REGISTER_SUBTITLE]: 'Створіть акаунт, щоб почати свою кавову подорож',
    [LOCALE_KEYS.AUTH_FULL_NAME]: 'Повне ім\'я',
    [LOCALE_KEYS.AUTH_EMAIL]: 'Електронна пошта',
    [LOCALE_KEYS.AUTH_PASSWORD]: 'Пароль',
    [LOCALE_KEYS.AUTH_SIGN_IN]: 'Увійти',
    [LOCALE_KEYS.AUTH_CREATE_ACCOUNT]: 'Створити акаунт',
    [LOCALE_KEYS.AUTH_NO_ACCOUNT]: "Немає акаунта? Зареєструватися",
    [LOCALE_KEYS.AUTH_HAVE_ACCOUNT]: "Вже є акаунт? Увійти"
  }
};

export const useLocaleStore = create((set) => ({
  locale: 'en',
  setLocale: (locale) => set({ locale }),
}));

export function useTranslation() {
  const { locale, setLocale } = useLocaleStore();

  const t = (key) => {
    return translations[locale][key] || key;
  };

  return { t, locale, setLocale };
}
